import type {
  BoundedContextDeclaration,
  ConnectionsDeclaration,
} from "@rta/vocab"
import {
  deriveConnectionsObligations,
  deriveContextObligations,
  formatObligationMarker,
  type Obligation,
} from "../obligations.js"
import { formatGeneratedHeader } from "../generated-files.js"

export interface GeneratedTestFile {
  readonly relativePath: string
  readonly content: string
}

const primitivePath = (obligation: Obligation) =>
  obligation.aggregate !== undefined
    ? `${obligation.context}/${obligation.aggregate}.${obligation.primitiveName}.obligations.test.ts`
    : `${obligation.context}/${obligation.primitiveName}.obligations.test.ts`

const groupByPrimitive = (obligations: ReadonlyArray<Obligation>) => {
  const grouped = new Map<string, Obligation[]>()
  for (const obligation of obligations) {
    const key = primitivePath(obligation)
    if (!grouped.has(key)) grouped.set(key, [])
    grouped.get(key)!.push(obligation)
  }
  return grouped
}

const describeLabel = (obligation: Obligation) =>
  obligation.aggregate !== undefined
    ? `${obligation.context}.${obligation.aggregate}.${obligation.primitiveName}`
    : `${obligation.context}.${obligation.primitiveName}`

const todoLabel = (obligation: Obligation) =>
  `${obligation.primitiveType} obligation: ${obligation.description}`

export const generateObligationTests = (
  contexts: ReadonlyArray<BoundedContextDeclaration>,
  connections: ReadonlyArray<ConnectionsDeclaration>,
  vocabHash: string,
): ReadonlyArray<GeneratedTestFile> => {
  const obligations = [
    ...contexts.flatMap((context) => deriveContextObligations(context)),
    ...connections.flatMap((connection) => deriveConnectionsObligations(connection)),
  ]

  return [...groupByPrimitive(obligations).entries()].map(([relativePath, primitiveObligations]) => {
    const first = primitiveObligations[0]!
    return {
      relativePath,
      content: [
        formatGeneratedHeader(vocabHash),
        "// Generated by rta generate — obligation stub. Keep and implement.",
        "",
        'import { describe, it } from "vitest"',
        "",
        `describe(${JSON.stringify(describeLabel(first))}, () => {`,
        ...primitiveObligations.flatMap((obligation) => [
          `  // ${formatObligationMarker(obligation.id)}`,
          `  it.todo(${JSON.stringify(todoLabel(obligation))})`,
          "",
        ]),
        "})",
        "",
      ].join("\n"),
    }
  })
}
