import type {
  BoundedContextDeclaration,
  ConnectionsDeclaration,
} from "@rta/vocab"
import { formatGeneratedHeader } from "../generated-files.js"
import {
  deriveConnectionsOperationEventContracts,
  deriveContextOperationEventContracts,
  formatOperationEventMarker,
  type OperationEventContract,
} from "../operation-events.js"

export interface GeneratedOperationEventTestFile {
  readonly relativePath: string
  readonly content: string
}

const primitivePath = (contract: OperationEventContract) =>
  contract.aggregate !== undefined
    ? `${contract.context}/${contract.aggregate}.${contract.primitiveName}.operation-events.test.ts`
    : `${contract.context}/${contract.primitiveName}.operation-events.test.ts`

const groupByPrimitive = (items: ReadonlyArray<OperationEventContract>) => {
  const grouped = new Map<string, OperationEventContract[]>()
  for (const item of items) {
    const key = primitivePath(item)
    if (!grouped.has(key)) grouped.set(key, [])
    grouped.get(key)!.push(item)
  }
  return grouped
}

const describeLabel = (item: OperationEventContract) =>
  item.aggregate !== undefined
    ? `${item.context}.${item.aggregate}.${item.primitiveName}.operation-events`
    : `${item.context}.${item.primitiveName}.operation-events`

export const generateOperationEventTests = (
  contexts: ReadonlyArray<BoundedContextDeclaration>,
  connections: ReadonlyArray<ConnectionsDeclaration>,
  hash: string,
): ReadonlyArray<GeneratedOperationEventTestFile> => {
  const contracts = [
    ...contexts.flatMap((context) => deriveContextOperationEventContracts(context)),
    ...connections.flatMap((connection) => deriveConnectionsOperationEventContracts(connection)),
  ]

  return [...groupByPrimitive(contracts).entries()].map(([relativePath, primitiveContracts]) => {
    const first = primitiveContracts[0]!
    const lines = [
      formatGeneratedHeader(hash),
      "// Generated by rta generate — operation event contract stub. Keep and implement.",
      "",
      "import { describe, it } from \"vitest\"",
      "",
      `describe(${JSON.stringify(describeLabel(first))}, () => {`,
      ...primitiveContracts.flatMap((contract) => [
        `  // ${formatOperationEventMarker(contract.id)}`,
        `  // required phases: ${contract.requiredPhases.join(", ")}`,
        `  it.todo(${JSON.stringify(`operation events: ${contract.description}`)})`,
        "",
      ]),
      "})",
      "",
    ]
    return {
      relativePath,
      content: lines.join("\n"),
    }
  })
}
