import type { BoundedContextDeclaration, ConnectionsDeclaration } from "@rta/vocab"

// ---------------------------------------------------------------------------
// Generate registry.ts — combined command/query registry for all contexts
// ---------------------------------------------------------------------------

export interface GenerateRegistryOptions {
  readonly strict: boolean
}

const toPascalCase = (s: string): string =>
  s.charAt(0).toUpperCase() + s.slice(1)

const indent = (s: string, n = 2): string =>
  s
    .split("\n")
    .map((l) => (l.trim() ? " ".repeat(n) + l : l))
    .join("\n")

export const generateRegistry = (
  contexts: ReadonlyArray<BoundedContextDeclaration>,
  connections: ReadonlyArray<ConnectionsDeclaration>,
  options: GenerateRegistryOptions,
): string => {
  const { strict } = options

  // Index connections by context name for fast lookup
  const connByContext = new Map<string, ConnectionsDeclaration>()
  for (const c of connections) {
    connByContext.set(c.context, c)
  }

  // Build per-context data
  interface ContextEntry {
    ctx: BoundedContextDeclaration
    commands: Array<{ cmdName: string; aggName: string }>
    queries: Array<{ queryName: string }>
    reactions: Array<{ reactionName: string; triggerEvent: string }>
    repos: Array<string> // agg names
    conn: ConnectionsDeclaration | undefined
  }

  const entries: ContextEntry[] = contexts.map((ctx) => {
    const aggregates = ctx.aggregates ?? []
    return {
      ctx,
      commands: aggregates.flatMap((agg) =>
        (agg.commands ?? []).map((cmd) => ({ cmdName: cmd.name, aggName: agg.name })),
      ),
      queries: (ctx.queries ?? []).map((q) => ({ queryName: q.name })),
      reactions: (connByContext.get(ctx.name)?.reactions ?? []).map((reaction) => ({
        reactionName: reaction.name,
        triggerEvent: reaction.trigger.event,
      })),
      repos: aggregates.map((a) => toPascalCase(a.name)),
      conn: connByContext.get(ctx.name),
    }
  })

  const lines: string[] = []

  // Header
  lines.push("// Generated by rta generate — do not edit")
  lines.push("")

  // Top-level imports
  const hasAnyHandlers = entries.some(
    (e) => e.commands.length > 0 || e.queries.length > 0 || e.reactions.length > 0,
  )

  if (!hasAnyHandlers) {
    lines.push("// No commands or queries found across all contexts.")
    lines.push("export const registry = {}")
    lines.push("")
    return lines.join("\n")
  }

  if (strict) {
    lines.push(`import { Effect, Layer } from "effect"`)
    lines.push(`import { ContextFactory, type OperationScope } from "@rta/core"`)
    lines.push(`import { makeConnectionMapLayer } from "@rta/strict"`)
  } else {
    lines.push(`import { Effect, Layer } from "effect"`)
  }
  lines.push("")

  // Per-context imports
  for (const { ctx, commands, queries, reactions, repos } of entries) {
    if (commands.length === 0 && queries.length === 0 && reactions.length === 0) continue

    const ctxName = ctx.name

    if (commands.length > 0) {
      const names = commands.map((c) => toPascalCase(c.cmdName))
      lines.push(`import { ${names.join(", ")} } from "./${ctxName}/commands.js"`)
    }
    if (queries.length > 0) {
      const names = queries.map((q) => toPascalCase(q.queryName))
      lines.push(`import { ${names.join(", ")} } from "./${ctxName}/queries.js"`)
    }
    for (const { cmdName } of commands) {
      const cmd = toPascalCase(cmdName)
      lines.push(
        `import { handle${cmd} } from "./${ctxName}/${cmd}Handler.js"`,
      )
    }
    for (const { queryName } of queries) {
      const q = toPascalCase(queryName)
      lines.push(
        `import { handle${q} } from "./${ctxName}/${q}Handler.js"`,
      )
    }
    for (const { reactionName } of reactions) {
      const reaction = toPascalCase(reactionName)
      lines.push(
        `import { handle${reaction} } from "./${ctxName}/${reaction}Handler.js"`,
      )
    }
    for (const repoName of repos) {
      lines.push(
        `import { ${repoName}RepositoryInMemory } from "./${ctxName}/${repoName}Repository.js"`,
      )
      lines.push(
        `import { _${repoName.charAt(0).toLowerCase() + repoName.slice(1)}Store } from "./${ctxName}/${repoName}Repository.js"`,
      )
    }
    lines.push("")
  }

  // Per-context layers and inline connection data (strict only)
  for (const { ctx, commands, queries, reactions, repos, conn } of entries) {
    if (commands.length === 0 && queries.length === 0 && reactions.length === 0) continue

    const varPrefix = ctx.name.charAt(0).toLowerCase() + ctx.name.slice(1)

    if (strict && conn) {
      // Inline the connections data so the registry file is self-contained
      const publishes = (conn.publishes ?? []).map(
        (p) =>
          `    { event: ${JSON.stringify(p.event)}, to: ${JSON.stringify(p.to)} as const }`,
      )
      const subscribes = (conn.subscribes ?? []).map(
        (s) =>
          `    { event: ${JSON.stringify(s.event)}, from: ${JSON.stringify(s.from)} }`,
      )
      lines.push(`const ${varPrefix}Connections = [{`)
      lines.push(`  kind: "Connections" as const,`)
      lines.push(`  context: ${JSON.stringify(ctx.name)},`)
      if (publishes.length > 0) {
        lines.push(`  publishes: [`)
        lines.push(publishes.join(",\n"))
        lines.push(`  ],`)
      } else {
        lines.push(`  publishes: [],`)
      }
      if (subscribes.length > 0) {
        lines.push(`  subscribes: [`)
        lines.push(subscribes.join(",\n"))
        lines.push(`  ],`)
      } else {
        lines.push(`  subscribes: [],`)
      }
      lines.push(`}]`)
      lines.push(
        `const ${varPrefix}ConnectionMapLayer = makeConnectionMapLayer(${varPrefix}Connections)`,
      )
      lines.push("")
    }

    const repoLayers = repos.map((r) => `${r}RepositoryInMemory`)
    const allLayers =
      strict && conn
        ? [...repoLayers, `${varPrefix}ConnectionMapLayer`]
        : repoLayers

    if (allLayers.length === 1) {
      lines.push(`const ${varPrefix}Layer = ${allLayers[0]}`)
    } else if (allLayers.length > 1) {
      lines.push(
        `const ${varPrefix}Layer = Layer.mergeAll(${allLayers.join(", ")})`,
      )
    } else {
      lines.push(`const ${varPrefix}Layer = Layer.empty`)
    }
    lines.push("")
  }

  // Registry object
  lines.push("export const registry = {")

  for (const { ctx, commands, queries, reactions } of entries) {
    if (commands.length === 0 && queries.length === 0 && reactions.length === 0) continue

    const varPrefix = ctx.name.charAt(0).toLowerCase() + ctx.name.slice(1)

    for (const { cmdName } of commands) {
      const cmd = toPascalCase(cmdName)
      const key = `${ctx.name}.${cmdName}`
      lines.push(indent(`${JSON.stringify(key)}: {`))
      lines.push(indent(`kind: "command" as const,`, 4))
      lines.push(indent(`make: ${cmd}.make,`, 4))
      lines.push(indent(`handle: handle${cmd},`, 4))
      lines.push(indent(`layer: ${varPrefix}Layer,`, 4))
      lines.push(indent(`},`))
    }

    for (const { queryName } of queries) {
      const q = toPascalCase(queryName)
      const key = `${ctx.name}.${queryName}`
      lines.push(indent(`${JSON.stringify(key)}: {`))
      lines.push(indent(`kind: "query" as const,`, 4))
      lines.push(indent(`make: ${q}.make,`, 4))
      lines.push(indent(`handle: handle${q},`, 4))
      lines.push(indent(`layer: ${varPrefix}Layer,`, 4))
      lines.push(indent(`},`))
    }

    for (const { reactionName, triggerEvent } of reactions) {
      const reaction = toPascalCase(reactionName)
      const key = `${ctx.name}.${reactionName}`
      lines.push(indent(`${JSON.stringify(key)}: {`))
      lines.push(indent(`kind: "event" as const,`, 4))
      lines.push(indent(`trigger: ${JSON.stringify(triggerEvent)},`, 4))
      lines.push(indent(`handle: handle${reaction},`, 4))
      lines.push(indent(`layer: ${varPrefix}Layer,`, 4))
      lines.push(indent(`},`))
    }
  }

  lines.push("}")
  lines.push("")

  if (strict) {
    lines.push(`export type RegistryOperation = keyof typeof registry`)
    lines.push(`export type RegistryEntry = (typeof registry)[RegistryOperation]`)
    lines.push(`type DispatchEntry = {`)
    lines.push(`  readonly kind: "command" | "query" | "event"`)
    lines.push(`  readonly make?: unknown`)
    lines.push(`  readonly handle: unknown`)
    lines.push(`  readonly layer: unknown`)
    lines.push(`}`)
    lines.push("")
    lines.push(`const asDispatchEntry = (entry: RegistryEntry): DispatchEntry => entry as unknown as DispatchEntry`)
    lines.push("")
    lines.push(`const createDispatchScope = (operation: string, kind: DispatchEntry["kind"], scope?: OperationScope): OperationScope => {`)
    lines.push(`  if (scope) return scope`)
    lines.push(`  const external = new ContextFactory().createExternal({ actorId: "generated-registry" })`)
    lines.push(`  if (kind === "command") {`)
    lines.push(`    return external`)
    lines.push(`      .promote("internal", { message: \`validated generated registry input for \${operation}\` })`)
    lines.push(`      .promote("command", { message: \`dispatch generated command \${operation}\` })`)
    lines.push(`  }`)
    lines.push(`  return external.promote("internal", { message: \`dispatch generated query \${operation}\` })`)
    lines.push(`}`)
    lines.push("")
    lines.push(`export const dispatch = (`)
    lines.push(`  operation: RegistryOperation,`)
    lines.push(`  raw: unknown,`)
    lines.push(`  scope?: OperationScope,`)
    lines.push(`): Effect.Effect<unknown, unknown, never> => {`)
    lines.push(`  const entry = asDispatchEntry(registry[operation] as RegistryEntry)`)
    lines.push(`  const dispatchScope = createDispatchScope(String(operation), entry.kind, scope)`)
    lines.push(`  if (entry.kind === "event") {`)
    lines.push(`    const handle = entry.handle as (message: any, scope: OperationScope) => Effect.Effect<unknown, unknown, unknown>`)
    lines.push(`    return Effect.provide(handle(raw, dispatchScope), entry.layer as any) as Effect.Effect<unknown, unknown, never>`)
    lines.push(`  }`)
    lines.push(`  const commandOrQuery = entry`)
    lines.push(`  const decode = commandOrQuery.make as (raw: unknown, context: unknown) => Effect.Effect<any, unknown, never>`)
    lines.push(`  const handle = commandOrQuery.handle as (message: any, scope: OperationScope) => Effect.Effect<unknown, unknown, unknown>`)
    lines.push(`  const messageContext = commandOrQuery.kind === "command"`)
    lines.push(`    ? {`)
    lines.push(`        correlationId: dispatchScope.traceId,`)
    lines.push(`        causationId: dispatchScope.operationId,`)
    lines.push(`        issuedAt: dispatchScope.clock.now(),`)
    lines.push(`        issuedBy: dispatchScope.identity.actorId,`)
    lines.push(`      }`)
    lines.push(`    : {`)
    lines.push(`        correlationId: dispatchScope.traceId,`)
    lines.push(`        issuedBy: dispatchScope.identity.actorId,`)
    lines.push(`      }`)
    lines.push(`  const handled = Effect.flatMap(decode(raw, messageContext), (message) => handle(message, dispatchScope))`)
    lines.push(`  return Effect.provide(handled, commandOrQuery.layer as any) as Effect.Effect<unknown, unknown, never>`)
    lines.push(`}`)
    lines.push("")
    lines.push(`export const dispatchCommand = (`)
    lines.push(`  operation: Extract<RegistryOperation, string>,`)
    lines.push(`  raw: unknown,`)
    lines.push(`  scope?: OperationScope,`)
    lines.push(`): Effect.Effect<void, unknown, never> => {`)
    lines.push(`  const entry = asDispatchEntry(registry[operation as RegistryOperation] as RegistryEntry)`)
    lines.push(`  return entry.kind === "command"`)
    lines.push(`    ? dispatch(operation as RegistryOperation, raw, scope).pipe(Effect.asVoid)`)
    lines.push(`    : Effect.die(new Error(\`\${operation} is not a command\`))`)
    lines.push(`}`)
    lines.push("")
    lines.push(`export const dispatchQuery = (`)
    lines.push(`  operation: Extract<RegistryOperation, string>,`)
    lines.push(`  raw: unknown,`)
    lines.push(`  scope?: OperationScope,`)
    lines.push(`): Effect.Effect<unknown, unknown, never> => {`)
    lines.push(`  const entry = asDispatchEntry(registry[operation as RegistryOperation] as RegistryEntry)`)
    lines.push(`  return entry.kind === "query"`)
    lines.push(`    ? dispatch(operation as RegistryOperation, raw, scope)`)
    lines.push(`    : Effect.die(new Error(\`\${operation} is not a query\`))`)
    lines.push(`}`)
    lines.push("")
    lines.push(`export const dispatchEvent = (`)
    lines.push(`  operation: Extract<RegistryOperation, string>,`)
    lines.push(`  event: unknown,`)
    lines.push(`  scope?: OperationScope,`)
    lines.push(`): Effect.Effect<void, unknown, never> => {`)
    lines.push(`  const entry = asDispatchEntry(registry[operation as RegistryOperation] as RegistryEntry)`)
    lines.push(`  return entry.kind === "event"`)
    lines.push(`    ? dispatch(operation as RegistryOperation, event, scope).pipe(Effect.asVoid)`)
    lines.push(`    : Effect.die(new Error(\`\${operation} is not an event handler\`))`)
    lines.push(`}`)
    lines.push("")
  }

  // Stores export
  lines.push("export const stores: Record<string, Map<string, unknown>> = {")
  for (const { ctx, repos } of entries) {
    if (repos.length === 0) continue
    for (const repoName of repos) {
      const aggName = repoName  // repoName is already PascalCase aggregate name
      lines.push(indent(`${JSON.stringify(`${ctx.name}.${aggName}`)}: _${repoName.charAt(0).toLowerCase() + repoName.slice(1)}Store as Map<string, unknown>,`))
    }
  }
  lines.push("}")
  lines.push("")

  return lines.join("\n")
}
