import type {
  BoundedContextDeclaration,
  ConnectionsDeclaration,
} from "@rta/vocab"
import {
  deriveConnectionsTelemetry,
  deriveContextTelemetry,
  formatTelemetryMarker,
  type ExecutionTelemetryExpectation,
} from "../telemetry.js"
import { formatGeneratedHeader } from "../generated-files.js"

export interface GeneratedTelemetryTestFile {
  readonly relativePath: string
  readonly content: string
}

const primitivePath = (expectation: ExecutionTelemetryExpectation) =>
  expectation.aggregate !== undefined
    ? `${expectation.context}/${expectation.aggregate}.${expectation.primitiveName}.telemetry.test.ts`
    : `${expectation.context}/${expectation.primitiveName}.telemetry.test.ts`

const groupByPrimitive = (items: ReadonlyArray<ExecutionTelemetryExpectation>) => {
  const grouped = new Map<string, ExecutionTelemetryExpectation[]>()
  for (const item of items) {
    const key = primitivePath(item)
    if (!grouped.has(key)) grouped.set(key, [])
    grouped.get(key)!.push(item)
  }
  return grouped
}

const describeLabel = (item: ExecutionTelemetryExpectation) =>
  item.aggregate !== undefined
    ? `${item.context}.${item.aggregate}.${item.primitiveName}.telemetry`
    : `${item.context}.${item.primitiveName}.telemetry`

export const generateTelemetryTests = (
  contexts: ReadonlyArray<BoundedContextDeclaration>,
  connections: ReadonlyArray<ConnectionsDeclaration>,
  vocabHash: string,
): ReadonlyArray<GeneratedTelemetryTestFile> => {
  const expectations = [
    ...contexts.flatMap((context) => deriveContextTelemetry(context)),
    ...connections.flatMap((connection) => deriveConnectionsTelemetry(connection)),
  ]

  return [...groupByPrimitive(expectations).entries()].map(([relativePath, items]) => {
    const first = items[0]!
    return {
      relativePath,
      content: [
        formatGeneratedHeader(vocabHash),
        "// Generated by rta generate — execution telemetry stub. Keep and implement.",
        "",
        'import { describe, it } from "vitest"',
        "",
        `describe(${JSON.stringify(describeLabel(first))}, () => {`,
        ...items.flatMap((item) => [
          `  // ${formatTelemetryMarker(item.id)}`,
          `  // phases: ${item.phases.join(", ")}`,
          `  it.todo(${JSON.stringify(`execution telemetry: ${item.description}`)})`,
          "",
        ]),
        "})",
        "",
      ].join("\n"),
    }
  })
}
