// @rta-generated vocab-hash:52033c12594a5716e045dcb64a3c3c10f8f4950148c0f3aeeab5dcbd827b9319
// Generated by rta generate — obligation stub. Keep and implement.

import { describe, it } from "vitest"

describe("Billing.CreateInvoiceOnSlotBooked", () => {
  // @rta-obligation reaction:Billing.CreateInvoiceOnSlotBooked:trigger-handled
  it.todo("reaction obligation: reaction handles SlotBooked")

  // @rta-obligation reaction:Billing.CreateInvoiceOnSlotBooked:emit:CreateInvoice:to:Billing
  it.todo("reaction obligation: reaction emits CreateInvoice to Billing")

})
