// @rta-generated vocab-hash:e80ee1788c51f106995f34feaa0656ec5b2c1a0f63b702c0ac4d6fcd55586c84
// Generated by rta generate — obligation stub. Keep and implement.

import { describe, it } from "vitest"

describe("Billing.CreateInvoiceOnSlotBooked", () => {
  // @rta-obligation reaction:Billing.CreateInvoiceOnSlotBooked:trigger-handled
  it.todo("reaction obligation: reaction handles SlotBooked")

  // @rta-obligation reaction:Billing.CreateInvoiceOnSlotBooked:emit:CreateInvoice:to:Billing
  it.todo("reaction obligation: reaction emits CreateInvoice to Billing")

})
