// @rta-generated vocab-hash:56c2dbca0afaac7a92ec8cb18698354a0c54afa7bc5a3f91a90b53669f3e992f
// Generated by rta generate — obligation stub. Keep and implement.

import { describe, it } from "vitest"

describe("Billing.CreateInvoiceOnSlotBooked", () => {
  // @rta-obligation reaction:Billing.CreateInvoiceOnSlotBooked:trigger-handled
  it.todo("reaction obligation: reaction handles SlotBooked")

  // @rta-obligation reaction:Billing.CreateInvoiceOnSlotBooked:emit:CreateInvoice:to:Billing
  it.todo("reaction obligation: reaction emits CreateInvoice to Billing")

})
