import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { deriveAll } from "../derivation/index.mjs";

export function generateAppCli({ root, app }) {
  const outDir = join(root, ".rta", "generated", app.name);
  mkdirSync(outDir, { recursive: true });
  const defaultScenario = app.scenarios?.find((scenario) => scenario.id.includes("integrated"))?.id ?? app.scenarios?.[0]?.id;
  const hash = derivationHash(app);
  const content = `#!/usr/bin/env node
${generatedTextHeader({ policy: "always-regenerated", hash, source: "rta.app.json" })}import { spawnSync } from "node:child_process";
import { resolve } from "node:path";

const root = resolve(new URL("../../..", import.meta.url).pathname);
const args = process.argv.slice(2);
const command = args[0] ?? "run";
const rest = args.slice(1);
const defaultScenario = ${JSON.stringify(defaultScenario)};
const rtaArgs = route(command, rest);
const res = spawnSync("node", ["scripts/rta.mjs", ...rtaArgs], {
  cwd: root,
  stdio: "inherit",
});
process.exit(res.status ?? 1);

function route(command, rest) {
  if (command === "run") return ["scenario", "run", scenarioFrom(rest), ...withoutScenario(rest)];
  if (command === "watch") return ["scenario", "watch", scenarioFrom(rest), ...withoutScenario(rest)];
  if (command === "replay") return ["scenario", "replay", rest[0]];
  if (command === "queue") return ["queue", ...rest];
  if (command === "scheduler") return ["scheduler", ...rest];
  if (command === "review") return ["review", ...rest];
  if (command === "publish") return ["publish", ...rest];
  if (command === "help" || command === "--help") return ["help"];
  return ["scenario", "run", defaultScenario, command, ...rest];
}

function scenarioFrom(rest) {
  const scenarioIndex = rest.indexOf("--scenario");
  return scenarioIndex >= 0 ? rest[scenarioIndex + 1] : defaultScenario;
}

function withoutScenario(rest) {
  const scenarioIndex = rest.indexOf("--scenario");
  return scenarioIndex >= 0
    ? rest.filter((arg, index) => index !== scenarioIndex && index !== scenarioIndex + 1)
    : rest;
}
`;
  const path = join(outDir, `${app.name}.mjs`);
  writeFileSync(path, content, { mode: 0o755 });
  return path;
}

export function generateAppScaffold({ root, app, outDir }) {
  const target = join(root, outDir);
  const hash = derivationHash(app);
  mkdirSync(join(target, "bin"), { recursive: true });
  mkdirSync(join(target, "src"), { recursive: true });
  mkdirSync(join(target, "scenarios"), { recursive: true });
  writeFileSync(join(target, "rta.app.json"), JSON.stringify({
    generated: { policy: "generated-once", derivationHash: hash, source: "rta.app.json" },
    ...app,
  }, null, 2));
  writeFileSync(join(target, "README.md"), generatedTextHeader({ policy: "generated-once", hash, source: "rta.app.json" }) + `# ${app.name}

Generated RTA app scaffold.

## Commands

\`\`\`bash
node bin/${app.name}.mjs --help
\`\`\`
`);
  writeFileSync(join(target, "bin", `${app.name}.mjs`), `#!/usr/bin/env node
${generatedTextHeader({ policy: "always-regenerated", hash, source: "rta.app.json" })}console.log(${JSON.stringify(`${app.name} scaffold generated by RTA`)});
`, { mode: 0o755 });
  writeFileSync(join(target, "src", "app.mjs"), generatedTextHeader({ policy: "manual-leaf", hash, source: "rta.app.json" }) + "export const app = {};\n");
  return target;
}

export function generateDerivationBundle({ root, app }) {
  const outDir = join(root, ".rta", "generated", app.name);
  mkdirSync(outDir, { recursive: true });
  const hash = derivationHash(app);
  const all = deriveAll(app);
  const files = {
    "derivation-manifest.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveAll", content: { app: app.name, files: [] } }),
    "obligations.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveObligations", content: all.obligations }),
    "telemetry.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveTelemetry", content: all.telemetry }),
    "operation-logs.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveOperationLogs", content: all.operationLogs }),
    "review-gates.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveReviewGates", content: all.reviewGates }),
    "use-case-obligations.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveUseCaseObligations", content: all.useCaseObligations }),
    "scenario-coverage.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveScenarioCoverage", content: all.scenarioCoverage }),
    "boundary-coverage.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveBoundaryCoverage", content: all.boundaryCoverage }),
    "runtime-contract.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveRuntimeContract", content: all.runtimeContract }),
    "app-runtime.schema.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveRuntimeContract", content: appRuntimeSchema(all.runtimeContract) }),
  };
  const manifestContent = {
    app: app.name,
    derivationHash: hash,
    policy: "always-regenerated",
    files: Object.keys(files).sort(),
  };
  files["derivation-manifest.json"] = generatedJson({ policy: "always-regenerated", hash, source: "deriveAll", content: manifestContent });
  for (const [name, content] of Object.entries(files)) writeFileSync(join(outDir, name), content);
  generateAppCli({ root, app });
  return outDir;
}

export function checkGeneratedSync({ root, app }) {
  const outDir = join(root, ".rta", "generated", app.name);
  if (!existsSync(outDir)) return [`generated bundle missing: run rta generate`];
  const expected = expectedGeneratedBundle(app);
  const errors = [];
  for (const [name, content] of Object.entries(expected)) {
    const path = join(outDir, name);
    if (!existsSync(path)) {
      errors.push(`missing generated file ${name}`);
      continue;
    }
    const actual = readFileSync(path, "utf8");
    if (actual !== content) errors.push(`generated file drifted: ${name}`);
  }
  return errors;
}

export function expectedGeneratedBundle(app) {
  const hash = derivationHash(app);
  const all = deriveAll(app);
  const files = {
    "obligations.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveObligations", content: all.obligations }),
    "telemetry.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveTelemetry", content: all.telemetry }),
    "operation-logs.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveOperationLogs", content: all.operationLogs }),
    "review-gates.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveReviewGates", content: all.reviewGates }),
    "use-case-obligations.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveUseCaseObligations", content: all.useCaseObligations }),
    "scenario-coverage.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveScenarioCoverage", content: all.scenarioCoverage }),
    "boundary-coverage.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveBoundaryCoverage", content: all.boundaryCoverage }),
    "runtime-contract.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveRuntimeContract", content: all.runtimeContract }),
    "app-runtime.schema.json": generatedJson({ policy: "always-regenerated", hash, source: "deriveRuntimeContract", content: appRuntimeSchema(all.runtimeContract) }),
  };
  files["derivation-manifest.json"] = generatedJson({
    policy: "always-regenerated",
    hash,
    source: "deriveAll",
    content: { app: app.name, derivationHash: hash, policy: "always-regenerated", files: Object.keys({ "derivation-manifest.json": "", ...files }).sort() },
  });
  return files;
}

export function derivationHash(app) {
  return createHash("sha256").update(JSON.stringify(deriveAll(app))).digest("hex").slice(0, 16);
}

function generatedJson({ policy, hash, source, content }) {
  return `${JSON.stringify({
    generated: { policy, derivationHash: hash, source },
    content,
  }, null, 2)}\n`;
}

function appRuntimeSchema(runtimeContract) {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "RTA AppRuntime",
    type: "object",
    required: ["app", "process", "ports", "targets"],
    properties: {
      app: { const: runtimeContract.app },
      process: { enum: runtimeContract.processes },
      ports: {
        type: "array",
        minItems: runtimeContract.ports.length,
        items: { enum: runtimeContract.ports },
      },
      targets: {
        type: "array",
        minItems: runtimeContract.targets.length,
        items: { enum: runtimeContract.targets },
      },
    },
  };
}

function generatedTextHeader({ policy, hash, source }) {
  return `// @generated by RTA\n// policy: ${policy}\n// derivationHash: ${hash}\n// source: ${source}\n`;
}
