import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function renderHomeLabIntent({ root, appName = "meeting-digest" }) {
  const outDir = join(root, ".rta", "hosting");
  mkdirSync(outDir, { recursive: true });
  const intent = `apiVersion: apps.virgil.info/v1alpha1
kind: WorkloadApp
metadata:
  name: ${appName}
spec:
  owner: rta
  description: RTA-authored meeting digest proving app
  image:
    source: local-authoring
  runtime:
    command: node examples/meeting-digest-seed/bin/meeting-digest.mjs --review
  access:
    public: false
    operatorOnly: true
  review:
    requiredBeforePublication: true
  observability:
    logs:
      humanReadable: true
      structured: true
  notes:
    - Generated by RTA hosting adapter.
    - This is intent only and does not deploy anything.
`;
  const path = join(outDir, `${appName}.workload-app.yaml`);
  writeFileSync(path, intent);
  return path;
}
