import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function renderHomeLabIntent({ root, appName = "meeting-digest", manifestPath = `deploy/apps/${appName}/manifests` }) {
  const outDir = join(root, ".rta", "hosting");
  mkdirSync(outDir, { recursive: true });
  const intent = `apiVersion: lab.virgil.info/v1alpha1
kind: WorkloadApp
serviceTier: internal

implementation:
  type: authored
  contractLevel: full

metadata:
  name: ${appName}
  tier: experiment
  version: 0.1.0
  description: RTA-authored meeting digest proving app.

delivery:
  argocd:
    application: ${appName}
    path: ${manifestPath}

runtime:
  namespace: ${appName}
  workload:
    type: Deployment
    name: ${appName}
  placement:
    prefer: tower

service:
  name: ${appName}
  portName: http
  port: 8080

routes: []

health:
  http:
    path: /health
    expectedStatus: 200
  checks:
    - name: web
      type: http
      required: true

data: []

observability:
  logs: true
  metrics: false
  alerts:
    - app-down

maintenance:
  automated:
    - kind: browser-smoke
      cadence: weekly
      required: false
      evidence: ops-journal
      persona: test-user
      status: planned
  human:
    - kind: admin-review
      cadence: monthly
      required: true
      evidence: ops-journal
`;
  const path = join(outDir, `${appName}.workload-app.yaml`);
  writeFileSync(path, intent);
  return path;
}

export function renderHomeLabDeploymentPackage({ root, appName = "meeting-digest", baseDir = join(root, ".rta", "hosting", "workload-apps"), manifestPath = null }) {
  const base = join(baseDir, appName);
  const manifests = join(base, "manifests");
  mkdirSync(manifests, { recursive: true });
  const appYaml = renderHomeLabIntent({ root, appName, manifestPath: manifestPath ?? relativePathFromPackage(baseDir, appName) });
  const appYamlText = `# Generated by RTA. Promote intentionally; do not apply blindly.\n${readGenerated(root, appYaml)}`;
  writeFileSync(join(base, "app.yaml"), appYamlText);
  writeFileSync(join(base, "application.yaml"), `apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${appName}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mjweavermount/rta
    targetRevision: HEAD
    path: .rta/hosting/workload-apps/${appName}/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ${appName}
  syncPolicy:
    automated: null
`);
  writeFileSync(join(manifests, "deployment.yaml"), `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appName}
  namespace: ${appName}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${appName}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${appName}
    spec:
      containers:
        - name: ${appName}
          image: node:22-alpine
          command: ["node", "-e", "require('http').createServer((req,res)=>{res.end('rta meeting digest ok')}).listen(8080)"]
          ports:
            - name: http
              containerPort: 8080
`);
  writeFileSync(join(manifests, "service.yaml"), `apiVersion: v1
kind: Service
metadata:
  name: ${appName}
  namespace: ${appName}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ${appName}
  ports:
    - name: http
      port: 8080
      targetPort: http
`);
  return base;
}

function relativePathFromPackage(baseDir, appName) {
  return `${baseDir}/${appName}/manifests`;
}

function readGenerated(_root, path) {
  return readFileSync(path, "utf8");
}
