import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function renderHostNeutralIntent({ root, appName = "meeting-digest" }) {
  const outDir = join(root, ".rta", "hosting");
  mkdirSync(outDir, { recursive: true });
  const intent = {
    app: appName,
    optionalHomeLab: true,
    image: `ghcr.io/mjweavermount/rta/${appName}:0.1.0`,
    process: {
      type: "http-health-plus-worker",
      command: ["node", ".rta/hosting/workload-apps/meeting-digest/health-server.mjs"],
    },
    health: {
      path: "/health",
      expectedStatus: 200,
    },
    adapters: ["local", "home-lab-workload-app"],
    promotion: {
      mode: "manual",
      note: "Generated package is draft output. Copy/promote intentionally into a host adapter repo.",
    },
  };
  const path = join(outDir, `${appName}.hosting-intent.json`);
  writeFileSync(path, JSON.stringify(intent, null, 2));
  return path;
}

export function renderHomeLabIntent({ root, appName = "meeting-digest", manifestPath = `deploy/apps/${appName}/manifests` }) {
  const outDir = join(root, ".rta", "hosting");
  mkdirSync(outDir, { recursive: true });
  const intent = `apiVersion: lab.virgil.info/v1alpha1
kind: WorkloadApp
serviceTier: internal

implementation:
  type: authored
  contractLevel: full

metadata:
  name: ${appName}
  tier: experiment
  version: 0.1.0
  description: RTA-authored meeting digest proving app.

delivery:
  argocd:
    application: ${appName}
    path: ${manifestPath}

runtime:
  namespace: ${appName}
  workload:
    type: Deployment
    name: ${appName}
  placement:
    prefer: tower

service:
  name: ${appName}
  portName: http
  port: 8080

routes: []

health:
  http:
    path: /health
    expectedStatus: 200
  checks:
    - name: web
      type: http
      required: true

data: []

observability:
  logs: true
  metrics: true
  alerts:
    - app-down

maintenance:
  automated:
    - kind: browser-smoke
      cadence: weekly
      required: false
      evidence: ops-journal
      persona: test-user
      status: planned
  human:
    - kind: admin-review
      cadence: monthly
      required: true
      evidence: ops-journal
`;
  const path = join(outDir, `${appName}.workload-app.yaml`);
  writeFileSync(path, intent);
  return path;
}

export function renderHomeLabDeploymentPackage({ root, appName = "meeting-digest", baseDir = join(root, ".rta", "hosting", "workload-apps"), manifestPath = null }) {
  const base = join(baseDir, appName);
  const manifests = join(base, "manifests");
  mkdirSync(manifests, { recursive: true });
  const hostIntentPath = renderHostNeutralIntent({ root, appName });
  const appYaml = renderHomeLabIntent({ root, appName, manifestPath: manifestPath ?? relativePathFromPackage(baseDir, appName) });
  const appYamlText = `# Generated by RTA. Promote intentionally; do not apply blindly.\n${readGenerated(root, appYaml)}`;
  writeFileSync(join(base, "hosting-intent.json"), readGenerated(root, hostIntentPath));
  writeFileSync(join(base, "Containerfile"), `FROM node:22-alpine
WORKDIR /app
COPY . .
EXPOSE 8080
CMD ["node", ".rta/hosting/workload-apps/${appName}/health-server.mjs"]
`);
  writeFileSync(join(base, "health-server.mjs"), `import http from "node:http";

const server = http.createServer((req, res) => {
  if (req.url === "/health") {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ status: "ok", app: ${JSON.stringify(appName)}, adapter: "rta-hosting" }));
    return;
  }
  res.writeHead(200, { "content-type": "text/plain" });
  res.end("RTA ${appName} hosting adapter ready\\n");
});

server.listen(8080);
`);
  writeFileSync(join(base, "app.yaml"), appYamlText);
  writeFileSync(join(base, "application.yaml"), `apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${appName}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mjweavermount/rta
    targetRevision: HEAD
    path: .rta/hosting/workload-apps/${appName}/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ${appName}
  syncPolicy:
    automated: null
`);
  writeFileSync(join(manifests, "deployment.yaml"), `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appName}
  namespace: ${appName}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${appName}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${appName}
    spec:
      containers:
        - name: ${appName}
          image: ghcr.io/mjweavermount/rta/${appName}:0.1.0
          imagePullPolicy: IfNotPresent
          command: ["node", ".rta/hosting/workload-apps/${appName}/health-server.mjs"]
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
`);
  writeFileSync(join(manifests, "service.yaml"), `apiVersion: v1
kind: Service
metadata:
  name: ${appName}
  namespace: ${appName}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ${appName}
  ports:
    - name: http
      port: 8080
      targetPort: http
`);
  writeFileSync(join(manifests, "healthcheck.yaml"), `apiVersion: v1
kind: ConfigMap
metadata:
  name: ${appName}-healthcheck
  namespace: ${appName}
data:
  path: /health
  expectedStatus: "200"
`);
  return base;
}

export function validateHomeLabDeploymentPackage({ root, appName = "meeting-digest", baseDir = join(root, ".rta", "hosting", "workload-apps") }) {
  const base = join(baseDir, appName);
  const required = [
    "hosting-intent.json",
    "Containerfile",
    "health-server.mjs",
    "app.yaml",
    "application.yaml",
    "manifests/deployment.yaml",
    "manifests/service.yaml",
    "manifests/healthcheck.yaml",
  ];
  const errors = required
    .filter((path) => !existsSync(join(base, path)))
    .map((path) => `hosting package missing ${path}`);
  if (errors.length > 0) return errors;

  const appYaml = readFileSync(join(base, "app.yaml"), "utf8");
  const deployment = readFileSync(join(base, "manifests", "deployment.yaml"), "utf8");
  const intent = JSON.parse(readFileSync(join(base, "hosting-intent.json"), "utf8"));
  if (!appYaml.includes("kind: WorkloadApp")) errors.push("app.yaml missing WorkloadApp");
  if (!appYaml.includes("contractLevel: full")) errors.push("app.yaml missing full contract level");
  if (!deployment.includes(`ghcr.io/mjweavermount/rta/${appName}:0.1.0`)) errors.push("deployment missing container image");
  if (!deployment.includes("readinessProbe") || !deployment.includes("livenessProbe")) errors.push("deployment missing health probes");
  if (intent.optionalHomeLab !== true) errors.push("hosting intent must keep home lab optional");
  return errors;
}

function relativePathFromPackage(baseDir, appName) {
  return `${baseDir}/${appName}/manifests`;
}

function readGenerated(_root, path) {
  return readFileSync(path, "utf8");
}
